<%@ Page Title="" Language="C#" MasterPageFile="~/HeardManager.Master" AutoEventWireup="true" CodeBehind="Main.aspx.cs" Inherits="HerdManager.Site.Main" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="outer">
        <div class="middle">
            <div class="MainCenter">
                <table id="MainTable">
                    <tr>
                        <td>
                            <asp:GridView ID="gdvAnimals" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="#666666" BorderStyle="Solid" BorderWidth="1px" EmptyDataText="Add a new animal." SelectedIndex="0" OnRowEditing="gdvAnimals_RowEditing" OnRowDeleting="gdvAnimals_RowDeleting">
                                <AlternatingRowStyle BackColor="Silver" BorderColor="Black" BorderStyle="Solid" BorderWidth="1px" />
                                <SelectedRowStyle BackColor="#0099CC" />
                            </asp:GridView>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <asp:LinkButton ID="lbtnAddNew" runat="server" Text="New Animal" PostBackUrl="~/Site/NewAnimal.aspx"></asp:LinkButton>
                            <asp:LinkButton ID="lbtnViewAnimal" runat="server">View Animal</asp:LinkButton>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</asp:Content>


